name: Attendance

on:
  schedule:
    - cron: '0 12 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  attendance:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-talenta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: cache-config
        uses: actions/cache@v2
        with:
          path: ~/.config/talenta
          key: ${{ runner.os }}-config

      - if: steps.cache-config.outputs.cache-hit != 'true'
        run: talenta login
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - run: talenta attendance --checkin-time 08:00 --checkout-time 16:30 -d wfh
