name: Attendance

on:
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  attendance:
    runs-on: ubuntu-20.04

    steps:
      - uses: el7cosmos/setup-talenta@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: cache-config
        uses: actions/cache@v2
        with:
          path: ~/.config/talenta
          key: ${{ runner.os }}-config

      - if: steps.cache-config.outputs.cache-hit != 'true'
        run: talenta login
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - run: talenta attendance --checkin-time 09:00 --checkout-time 18:00 -d wfh
