name: Test

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-talenta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: talenta --version
