name: Test

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run format-check
          npm run lint
          npm run package
        working-directory: ./.github/actions/setup-talenta
      - run: git diff --exit-code --ignore-all-space --compact-summary
        working-directory: ./.github/actions/setup-talenta
      - uses: ./.github/actions/setup-talenta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: talenta --version
